quickstart.php
=> Fix small typo

.htaccess.dev, Dockerfile, README.md, docker-compose.yml
This commit includes configuration for Docker to run the project using
only one command: 'docker-compose up'. Gone are the days of dealing with
a local install of Apache or, god forbid, XAMPP. A development htaccess
file has also been created which will only be used during the
development process and is left out of the source entirely for
production.
=> [Feature] Better development environment

public_html/lib/css/anim.css
@see https://developer.mozilla.org/en-US/docs/Web/CSS/@charset
=> Charset must be between double quotes

public_html/download.php
Download page says "Download the latest builds, source code and documentation". This change should make the source code more visible.
=> Link to the source code on GitHub in Download

public_html/faq.php, public_html/index.php, public_html/quickstart.php
By far the worst typo was "Unfortuently"
=> Got your typo fixes here

public_html/lib/module/in-specs.php
UPDATE.PUP -> PS3UPDAT.PUP, which is what it's really called.
=> Fix firmware filename

public_html/quickstart.php
* sorted the list
* added a note for Asus BC-12B1ST model that some revisions are not compatible (BC-12B1ST-20)
* added LG BU40N to the list as per today's info in discord
=> Update compatible drive list

public_html/about.php
- elad approved content
- hula approved grammar
=> add description about elad

public_html/lib/css/main.css, public_html/lib/css/scale.css
Didn't pay attention to the indentation style and used spaces instead of tabs in #39.
Also added a class to horizontally center objects. Forgot to add this as part of the original PR.
=> Fix formatting mistakes from previous PR

public_html/about.php, public_html/download.php, public_html/faq.php, public_html/index.php, public_html/latest-appimage.php, public_html/latest-windows.php, public_html/lib/module/sys-js.php
- **Support javascript-less browsers**
- Update Build function call from Compatibility submodule
- Update FAQ
- Update About
=> Support javascript-less browsers + October Updates

public_html/lib/module/ui-main-menu.php
Rather than just link directly to the forums, I think it's best to link directly to the thread that explains how to make a compatibility report.
=> Update testing contribution link

public_html/quickstart.php
Maybe it can be marked with the icon/hint instead ¯\_(ツ)_/¯
=> Mark external drive models

public_html/quickstart.php
Successfully dumped a couple of games with LG BH16NS60.
=> Add LG BH16NS60 drive

public_html/about.php, public_html/lib/css/main.css
Realised I never got around to adding myself and writing a description.
=> Add myself to the About page

public_html/download.php, public_html/latest-appimage.php, public_html/latest-windows.php
Build API was updated on the compatibility side
=> Update Build API calls

public_html/lib/module/sys-js.php
- Fixes index content not displaying
- Fixes unusable quickstart guide
- Slightly reduces quickstart sidebar size so it looks better
=> noscript: Fixes, experience improvements

public_html/lib/css/dark.css, public_html/lib/css/debug.css, public_html/lib/css/main.css
- Replace extensions that have been long replaced with their standardized versions
- Fix a few CSS syntax errors
=> css: Cleanup

public_html/about.php
=> Update my build specs

public_html/download.php
- **download: Fix HTML errors**
Validation is now green again
- **download: Gracefully handle missing plugin**
=> download: Gracefully handle missing plugin, fix HTML errors

public_html/lib/module/inc-specs.php
Add Windows 11
Remove Win10 2004 reference since it's EOL
Change recommended version from Win10 21H1 to Win10 21H2
Change latest Linux kernel from 5.16 to 5.17
Change minimum version from FreeBSD 12.2 (EOL) to FreeBSD 12.3
=> specs: Update minimum/recommended OS

public_html/download.php
- Update minimum version to 12.0
- Allow build to properly show as Unavailable when it's not present
=> download: macOS updates

public_html/quickstart.php
Reason for change
https://github.com/RPCS3/rpcs3/pull/13265
=> Follow up deprecate HDD0/disc in the QuickStart guide

public_html/lib/module/about/inc-about-current.php
I forgot to update the icons for my GPU and OS of my primary build.
Also, added details of the ROG Ally. Currently the icon for the Ally doesn't exist so I've just used a placeholder name "rog-ally.png"
=> Added ROG Ally and fix-up for other icons

public_html/lib/module/quickstart/inc-quickstart-device-requirement.php
Recommended CPU
Intel: Skylake (6th) -> Comet Lake (10th)
AMD: Zen 2 (3000) -> Zen 3 (5000)
Recommended RAM
8 GB -> 16 GB
Minimum RAM
4 GB -> 8 GB
=> quickstart: Updated recommended and minimum requirements

public_html/download.php, public_html/latest-appimage.php, public_html/latest-macos-arm64.php, public_html/latest-macos-x64.php, public_html/latest-windows.php, public_html/quickstart.php
- compat: Fix calls to get_latest()
- download: Add latest-macos x64 and arm64 permalinks
=> download: Add latest-macos x64 and arm64 permalinks

public_html/lib/module/menu/inc-menu-main.php, public_html/lib/module/rpcn/games.json, public_html/lib/module/rpcn/inc-rpcn-stats.php, public_html/rpcn.php
* Add a new page with RPCN players stats
* Hide Roadmap button
TODOs:
* CSS
* Refresh list serverside instead of clientside
Closes #117
=> Add RPCN player/game stats page

public_html/lib/module/rpcn/games.json
- GT HD Concept
- Neogeo
By @Ninetime
=> Add more ids to games.json

public_html/latest-appimage.php, public_html/latest-linux-arm64.php, public_html/latest-linux-x64.php
- https://rpcs3.net/latest-linux-x64
- https://rpcs3.net/latest-linux-arm64
- **wget:** `wget --content-disposition https://rpcs3.net/latest-linux-arm64`
- **curl:** `curl -JLO https://rpcs3.net/latest-linux-arm64`
=> Builds: Add permalinks to latest Linux x64/arm64 AppImage

public_html/lib/module/quickstart/inc-quickstart-dumping-drives.php
=> WP50NB40 is an External Drive

public_html/download.php
=> download: Fix link to latest macOS 13 arm64 build

public_html/lib/module/quickstart/inc-quickstart-device-inputs.php
Continue changes from https://github.com/DAGINATSUKO/www-rpcs3/pull/134/commits/8eb73509701448e1c9f09de4f2f48b1be0a795c3
=> Remove macOS 13 support

public_html/lib/module/download/inc-download-platform.php
=> download: Fix checksum for macOS arm64 builds

public_html/lib/module/download/inc-download-platform.php, public_html/lib/module/quickstart/inc-quickstart-software-download.php
Continue https://github.com/DAGINATSUKO/www-rpcs3/pull/138
Looks like a couple spots were missed just cleaning up.
=> Remove macOS 13 support again
