public_html/download.php
The existing instruction for "running" the RPCS3 AppImage on Linux simply explains how to make the file executable, not how to actually run it. This PR fixes that issue by adding the command to actually run the AppImage to that text box.
=> Fix Linux instruction in download.php

public_html/lib/css/main.css
Prevent .sha-spec labels from being selected when double-clicking the values. As of right now, double-clicking the SHA hash selects the "-256" part of "SHA-256" alongside with the actual hash value, which is rather annoying for the purposes of copying and comparison. Same happens with file sizes and PR version number.
=> Prevent .sha-spec labels from being accidently selected

public_html/quickstart.php
Adds LG BP50NB40 as a compatible drive to the list.  Successfully dumped games with it.
=> Update quickstart.php to include LG BP50NB40

public_html/quickstart.php
Added 2 LG drives that can read PS3 discs. One is an external, the other is an internal that can still be used with a SATA-to-USB adapter.
=> Added  extra LG BD-RE drives

public_html/about.php
I put a regular ampersand into the description about `elad`, which isn't nice in HTML, so here's a quick fix.
=> fix bad unicode character reference

public_html/quickstart.php
[LibRay](https://notabug.org/necklace/libray) is a Python application for dumping and decrypting PS3 discs, which seems to work really well on Linux, and does not require installing Mono or Wine like the current suggested tools in the QuickStart. Should be an easier and more convenient option for Linux users.
=> Add LibRay link to QuickStart (for Linux users)

public_html/lib/css/main.css, public_html/lib/css/menu.css
The Arial font is proprietary, and therefore not usually present on linux systems. This makes the website look quite weird, as almost everything falls through to browser default (usually a serif font). This PR allows the browser to fall back to a correct sans-serif style.
=> Add fallback for arial fonts in main.css and menu.css

README.md, public_html/lib/css/main.css, public_html/quickstart.php
With regards to the highlighted text, I've added `white-space:nowrap;` to prevent word wrap cutting important details into two lines. I've also removed the margins to the left and right as they end up creating too much space in a line and break the flow when used in progress reports. Will be easier to just add spaces where absolutely required.
**Before**
**After**
=> Changes to highlighted text + Typo fixes

public_html/download.php, public_html/lib/module/ui-main-menu.php, public_html/quickstart.php
Some users were getting confused with the heading placement and think the one-click PS3 dumper is Linux only.
**Before**
**After**
=> Move the One-click PS3 dumper header below the Linux option

public_html/lib/css/main.css, public_html/lib/css/scale.css
Most of our images in the blog are currently set using tables. This makes it almost impossible to see images on Mobiles. So, I've set up a new template using Flexbox that will automatically show images in the column format when viewed on Mobile. 
Some low-res images of the same (best I could do from my laptop):
**Look of a 2x2 on desktop:**
**Automatically changing to a column on Mobile:**
**Mobile before with tiny images:**
=> Allow use of Flexbox for images in the blog

public_html/lib/module/ui-main-specs.php
Removed DirectX dependency and moved the OpenSSL dependency to its spot.
=> Remove DirectX dependency from Quickstart guide

public_html/quickstart.php
Hi!
I've successfully created a backup of my God of War III (BCES-00510) blu ray with my LG CH12NS30 (fw. 1.00) and PS3 Disc Dumper on Windows 7. The backup is correctly seen and loaded on the latest RPCS3. I can confirm this drive is usable for backups.
Thank you!
=> Add LG CH12NS30 drive

public_html/download.php
Savedata is not an application directory.
I have asked where the app is stored and was informed that we should mention where the configuration data is instead. It appears the Mac jargon is Application Support. So update Download.php to be more accurate in the information provided.
Suggestions are welcome.
=> Savedata is not an application directory

public_html/quickstart.php
\dev_hdd0\disc has deprecated in favour of \games folder in RPCS3's root folder.
=> Updated to the correct directory that should be used for adding disc games to the emulator.

public_html/lib/module/inc-bdds.php
According to DeViL303 his Asus 14D1XT can also read PS3 Discs https://www.psx-place.com/threads/ps3-disc-dumper-for-pc.26232/
=> Add BW-14D1XT to compatbile blu-ray drive list

public_html/lib/module/quickstart/inc-quickstart-drives.php
BWU-500S is a retail version of BD-5300S
=> Update Optiarc drive models

public_html/lib/module/quickstart/inc-quickstart-dumping-tools.php
13x Disc dumper is available on Windows, Linux and macOS and it does the job for a user with just 1 button press instead of doing everything manually.
=> Remove outdated dumping bluray methods

public_html/lib/css/anim.css, public_html/lib/css/darkmode.css, public_html/lib/css/debug.css, public_html/lib/css/main.css, public_html/lib/css/scale.css
A broken formatting tool added a bunch of deprecated CSS properties, undoes those changes while preserving any actual CSS changes. Gets rid of all CSS warnings introduced by that commit.
=> lib/css: Undo unwanted changes from 5158eefa544fea465e8da83ffd4ec32bed82048c

public_html/download.php, public_html/lib/module/download/inc-download-platform.php, public_html/lib/module/quickstart/inc-quickstart-device-requirement.php
- download: Fix HTML syntax error
- download: Fix MSVC Redistributable version text
- download: Remove macOS 12.6 as supported, add macOS 15.0
- download: Remove FreeBSD 12.3 as supported, add FreeBSD 14.0
- download: Add download buttons for macOS 12 and macOS 11 legacy builds
- quickstart: Remove macOS 12.6 as supported, add macOS 15.0
- quickstart: Update Windows 11 recommendation from 23H2 to 24H2
=> download/quickstart: Update OS requirements, add macOS 12/11 legacy builds, fix syntax error

public_html/download.php, public_html/lib/module/download/inc-download-platform.php
The fallback is done on a per platform basis. If the latest version does not have an artifact for said platform, it will instead provide the artifact from the latest version that has one available for that platform.
Fixes #107
=> Download: Fallback to previous available build if unavailable
